#! /bin/sh

case "$1" in 
	start)
		echo "Starting simpleserver"
		start-stop-daemon -S -n simpleserver -a /usr/bin/aesdsocket
		;;
	stop)
		echo "Stopping simpleserver"
		start-stop-daemon -K -n simpleserver 
		;;
	*)
		echo "Uasge $0 {start|stop}"
	exit 1
esac

exit 0
