#! /bin/bash

cmd=""
proc_name=""
exec_path=""

while [ $# -gt 0 ]; do
	case $1 in
		-S|-K)
			cmd="$1"
			shift 1 
			;;
		-n)
			proc_name="$2"
			shift 2 
			;;
		-a) 
			exec_path="$2"
			shift 2 
			;;
		*)
			echo "Unknown option: $1"
			shift 1
			;;
	esac
done


case "$cmd" in
	-S)
		exec -a "$proc_name" "$exec_path" -d;;
	-K)
		kill `pidof "$proc_name"`;;
esac

